server.port=8082
spring.application.name=School-management-system
spring.datasource.url=jdbc:mysql://0.0.0.0:2020/school_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1998

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
#
#spring.flyway.locations=classpath:db/migration
#spring.flyway.enabled=true

logging.pattern.console= %d{yyyy-MMM-dd HH:mm:ss.SSS} %level **** %msg%n
logging.level.root = INFO
logging.level.lk.zerocode.School_management_system=DEBUG
logging.file.name=/home/udara/sms.log